### ISSUE TITLE
Return content of removed comments for mods

### ISSUE THREAD

**Issue by aeharding** [LemmyNet/lemmy#5232]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?

### Is your proposal related to a problem?

This issue stems from https://github.com/LemmyNet/lemmy/issues/5230. Essentially, I want to allow mods to view removed comments in a thread view. Since Lemmy removed the comment content for mods, I have to fetch each comment view the mod log with a separate request. This is very inefficient, and it would be nice to provide a way to bulk fetch comments in the modlog by id.

This issue is important for mods because right now if a mod nukes a chain, it's really annoying to have to step through the chain and view the mod log for each comment just in order to view the comment content.

### Describe the solution you'd like.

Bulk fetch comments in modlog by id

### Describe alternatives you've considered.

The alternative, as per https://github.com/LemmyNet/lemmy/issues/5230 (and old lemmy behavior) is to provide the comment content when fetching a comment thread for mods.

**Comment by dessalines** [comment]
Why not just have a `show removed comment` button for each one, and have it fetch on demand, and fill the comment box with the most recent removed content? Seems really inefficient to try to collect up all the removed ids for an entire thread, use a SQL in query to get them, then iterate through every response.

That's also not too ideal anyway, since its not going to show you the full history for that item.

**Comment by aeharding** [comment]
One example: It allows mods to go through and selectively approve comments after nuking a comment thread.

0clicks vs 20+ for large nukes (and more if you accidentally refresh…)


Also it’s much easier for mods to audit another mods bulk comment removal actions

**Comment by aeharding** [comment]
> That's also not too ideal anyway, since its not going to show you the full history for that item.

yah agreed. That’s why I prefer old Lemmy behavior, where comment content of removed comments is available for mods on original request. In lieu of that, though…

**Comment by DraconicNEO** [comment]
> Why not just have a `show removed comment` button for each one, and have it fetch on demand, and fill the comment box with the most recent removed content? Seems really inefficient to try to collect up all the removed ids for an entire thread, use a SQL in query to get them, then iterate through every response.
> 
> That's also not too ideal anyway, since its not going to show you the full history for that item.

I think that's a good idea, just being able to reveal removed comments is a good thing for being able to see context in a removed thread. Probably also a good idea for the ones which were removed silently without modlog posts, which is the case with ones removed automatically alongside a ban.

**Comment by aeharding** [comment]
> Probably also a good idea for the ones which were removed silently without modlog posts, which is the case with ones removed automatically alongside a ban.

I thought that was fixed recently. https://github.com/LemmyNet/lemmy/issues/4699

**Comment by DraconicNEO** [comment]
> > Probably also a good idea for the ones which were removed silently without modlog posts, which is the case with ones removed automatically alongside a ban.
> 
> I thought that was fixed recently. #4699

I'm not sure, if it has I'm not seeing the effects of it. I don't think it has though since I'm still not able to see them on any of my servers.

**Comment by Nutomic** [comment]
It would actually be pretty easy to return the content of removed comments only for admins. I made a PR for that in #5245. It doesnt mean that lemmy-ui will support this, so you may have to use different frontends or user scripts. It would also be much more complicated to do the same thing for mods (as each returned comment may belong to a different community).

**Comment by dessalines** [comment]
Yes it likely would be, although it will be a while before I can get to that, although it is a priority for `0.20.0`

**Comment by aeharding** [comment]
@dessalines awesome. I can close this issue and open a new one to address showing removed comment content for mods, with a note that it is blocked until #4365 is done.

LMK what is preferred!

**Comment by dessalines** [comment]
We can leave this open bc they're related, but I'll add it to the next milestone.
